workspace:
 base: /go
 path: src\github.com\josan053\drone-golang-example  #必須從src 開始

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  testing:
    image: golang:1.21.0
    commands:
      - go test -v .
      - go vet    

  build_linux_amd64:
    image: golang:1.21.0
    group : build
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -v -a -o release/linux/amd64/hellowworld

  build_linux_386:
    image: golang:1.21.0
    group : build
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=486
    commands:
      - go build -v -a -o release/linux/i386/hellowworld      