workspace:
 base: /go
 path: src\github.com\josan053\drone-golang-example  #必須從src 開始

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  testing:
    image: golang:1.21.0
    commands:
      - go test -v .
      - go vet    